### PR TITLE
Add Czech translation

### PR DESCRIPTION
**Pull request by daleckystepan**
Add Czech translation

### CODE REVIEW

**Comment by freshollie** [comment]
Brilliant! Thanks so much!

**Comment by daleckystepan** [comment]
You were faster than I expected :D We can polish it later. I didn't know exactly where are all strings visible. I will go through again.

**Comment by freshollie** [comment]
Ah sorry ;)

This is now deployed. It's worth noting that the ISO name for Czech is `cs` so I will change that. There are also some strings which are not showing that you have translated so I am looking into that.

I need to fix CI so that it deploys a preview branch for PRs, didn't seem to work

**Comment by daleckystepan** [comment]
Never mind. I will prepare another PR with fine tuning.

**Pull request merged**
