### PR TITLE
Swedish Buddy translations

### PR DESCRIPTION
**Pull request by ulfhedlund**
Swedish translations based on the Danish version by @HThuren . 
I have created the SE files by copying the text from the Danish json files and not by using the suggested 'yarn extract-locales' tool, simply because I'm not a programmer and don't understand how to set everything up. So it is untested...

### CODE REVIEW

**Comment by HThuren** [comment]
I did the same way :-)

**Review by HThuren — APPROVED** [review]
Look well

**Review by freshollie — APPROVED** [review]

**Comment by ulfhedlund** [comment]
Sorry I messed with the translations after you approved them. Won't do it again :)

**Comment by freshollie** [comment]
It’s fine, are you happy for me to merge now?

**Comment by ulfhedlund** [comment]
> It’s fine, are you happy for me to merge now?

Yes, thanks!

**Review by freshollie — APPROVED** [review]

**Pull request merged**
